spring:
  application:
    name: "bloggio-api"
  datasource:
    #url: ${URL_DB}
    url: jdbc:postgresql://dpg-d0sdulumcj7s73etvqdg-a.oregon-postgres.render.com/ferreteria_bd_jox5
    #username: ${USER_DB}
    username: ferreteria_bd_jox5_user
    #password: ${PASSWORD_DB}
    password: ImQNqIrO50qZncqPPclLpHEMMSsdr8J2
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher