spring:
  application:
    name: "bloggio-api"
  datasource:
    #url: ${URL_DB}
    url: jdbc:postgresql://dpg-cuasvbbtq21c73cfhac0-a.oregon-postgres.render.com/demo_k3mv
    #username: ${USER_DB}
    username: demo_k3mv_user
    #password: ${PASSWORD_DB}
    password: E8PtEuY522fkALXjvrPZ6edYgRwoswmf
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher