name: Java CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up cache
        run: |
          rm -rf ~/.cache/actions/*
          rm -rf ~/.local/share/actions/*

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Verify codestyle with Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        run: ./gradlew test

#      - name: Upload test coverage report (optional)
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-coverage-report
#          path: build/reports/jacoco/test/html/index.html